# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
 
trigger:
- master
 
pool:
  name: Azure Pipelines

# Set variables
variables:
  directory: $(System.DefaultWorkingDirectory)

stages:
- stage: dev_build
  displayName: Build Dev Solution
  jobs:  
  - job: Build
    displayName: Build and Publish Solution
    steps:
    - task: NodeTool@0
      displayName: 'Install node.js'
      inputs:
        versionSpec: '10.x'

    - script: 
        npm install
      displayName: 'npm install'
      workingDirectory: $(directory)
 
    - script: 
        set "REACT_APP_STAGE=$(stage)" && npm run build
      displayName: 'npm build'
      workingDirectory: $(directory)

    - task: CopyFiles@2
      displayName: 'Copy web.config to build folder'
      inputs:
        SourceFolder: '$(directory)/'
        Contents: 'web.config'
        TargetFolder: '$(directory)/build'

    - task: CopyFiles@2
      displayName: 'Copy maintenancepage.html to build folder'
      inputs:
        SourceFolder: '$(directory)/'
        Contents: 'maintenancepage.html'
        TargetFolder: '$(directory)/build'

    - task: PowerShell@2
      displayName: 'Replace config.js values for Development'
      inputs:
        targetType: 'inline'
        script: |
          $config_dest = "$(directory)\build\config.js"
          $content = "window.config = { CREDENTIALS_API_STATUS:'https://dev-waverify-api.doh.wa.gov', CREDENTIALS_API_QR:'https://dev-waverify-api.doh.wa.gov', CREDENTIALS_GA_DEPARTMENT: 'G-HHSVC4W7NS'};"
          echo $content | Set-Content $config_dest;
 
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: 'build'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs: 
        pathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

- stage: dev_deployment
  displayName: Deploy Development Solution
  dependsOn: [dev_build]
  jobs:
    - deployment: dev_deployment
      displayName: Deploy to Development Environment
      environment: Development
      strategy: 
        runOnce:
          deploy:
            steps:
            - task: DownloadBuildArtifacts@1
              displayName: 'Download Artifact'
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.ArtifactsDirectory)'
            - task: AzureRmWebAppDeployment@4
              displayName: 'Azure App Service Deployment'
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'DigitalCovid19VaccineServiceConnection'
                appType: 'webApp'
                WebAppName: 'app-txverify-ui-dev'
                packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'

